### ISSUE TITLE
SearchQueryOperator in organizations: serde rename values are rejected by API

### ISSUE THREAD

**Issue by graysonarts** [stytchauth/stytch-rust#35]
```rust
// src/b2b/organizations.rs#855-862
pub enum SearchQueryOperator {
    #[serde(rename = "or")]
    #[default]
    OR,
    #[serde(rename = "and")]
    AND,
}
```

With the renames, the API is rejecting them saying that they must be either "AND" or "OR". If I remove the renames so they are "AND" and "OR", then it works.

I believe the same is true for `M2MSearchQueryOperator` but not 100% sure

**Comment by ollie-stytch** [comment]
Hi @graysonarts thanks for flagging this! We just rolled out https://github.com/stytchauth/stytch-rust/commit/382372e273036a31c44a512e3b1622570931581e which should fix this issue. We had an issue with our codegen and have since fixed the issue. 

- Ollie
